apiVersion: v1
kind: Service
metadata:
  name: node-api-svc
spec:
  selector:
    app: node-api-depo
  ports:
    - protocol: TCP
      name: nodejs
      port: 80
      targetPort: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: node-db-svc
spec:
  selector:
    app: node-db-depo
  ports:
    - protocol: TCP
      port: 80
      targetPort: "http"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vue-bookshelf-depo
  name: vue-bookshelf-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: vue-bookshelf-depo
  type: NodePort
status:
  loadBalancer: {}